platform: linux

image_resource:
  type: docker-image
  source:
    repository: eugenmayer/make
    tag: latest

inputs:
  - name: input-version

outputs:
  - name: build_args

run:
  path: /bin/bash
  user: root
  args:
  - '-elc'
  - |
    export CI_BASE=`pwd`
    export RELEASE_VERSION=`cat ${CI_BASE}/input-version/number`
    echo "{\"RELEASE_VERSION\":\"${RELEASE_VERSION}\"}" > ${CI_BASE}/build_args/build_args.json
