groups:
- name: concourse-resources
  jobs:
  - build-docker-image-resource
- name: concourse-docker-images
  jobs:
  - build-docker-image-concourse-worker


jobs:
- name: build-docker-image-resource
  serial: true
  build_logs_to_retain: 100
  plan:
  - get: docker-image-resource
    trigger: true
  - task: build-docker-image-resource
    file: docker-image-resource/ci/build.yml
    input_mapping:
      docker-image-resource: docker-image-resource
    output_mapping:
      built-resource: docker-built-context
  - put: eugenmayer-docker-image-resource
    params:
      build: docker-built-context

- name: build-docker-image-concourse-worker
  serial: true
  build_logs_to_retain: 10
  plan:
  - get: docker-image-concourseci-worker-solid
    trigger: true
  - get: concourse-base-image
    trigger: true
    params:
      skip_download: true
  - put: concourse-worker-solid
    params:
      build: docker-image-concourseci-worker-solid

resources:
  - name: docker-image-resource
    type: git
    source:
      uri: https://github.com/EugenMayer/docker-image-resource-ng
      branch: develop

  - name: docker-image-concourseci-worker-solid
    type: git
    source:
      uri: https://github.com/EugenMayer/docker-image-concourseci-worker-solid
      branch: master

  - name: concourse-base-image
    type: docker-image
    source:
      repository: concourse/concourse
      tag: 3.6

  - name: concourse-worker-solid
    type: docker-image
    source:
      repository: eugenmayer/concourse-worker-solid
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: 3.6

  - name: eugenmayer-docker-image-resource
    type: docker-image
    source:
      repository: eugenmayer/concourse-docker-image-resource
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: latest