groups:
- name: misc
  jobs:
  - release-rundeck
- name: docker-tools
  jobs:
  - build-docker-image-docker-client
  - build-docker-s3fs-image
- name: concourse-resources
  jobs:
  - build-docker-image-resource
  - build-concourse-static-resource-image
- name: concourse-docker-images
  jobs:
  - build-docker-image-concourse-configurator
  - build-docker-image-concourse-worker-configurator
- name: atlassian-docker-images
  jobs:
  - build-docker-images-confluence
  - build-docker-images-jira
  - release-bitbucket-image

jobs:

### RUNDECK
- name: release-rundeck
  serial:                      true
  build_logs_to_retain:        5
  plan:
  - get:                     rundeck-version
    trigger:                 true
  - get:                     rundeck-repo
  - task: extract_build_version
    input_mapping:
      rundeck-version: rundeck-version
    output_mapping:
      builds_args: build_args
    file: rundeck-repo/ci/tasks/extract_version.yml
  - put: rundeck-image
    get_params: { skip_download : true }
    params:
      build: rundeck-repo
      build_args_file: build_args/build_args.json
      tag_as_latest: true
      cache_tag: latest
      tag: rundeck-version/number

### BITBUCKET
- name: release-bitbucket-image
  serial:                      true
  build_logs_to_retain:        5
  plan:
  - get:                     bitbucket-version
    trigger:                 true
  - get:                     bitbucket-repo
  - get:                     pipeline-src
  - task: extract_build_version
    input_mapping:
      input-version: bitbucket-version
    output_mapping:
      builds_args: build_args
    file: pipeline-src/ci/tasks/extract_version.yml
  - put: bitbucket-image
    get_params: { skip_download : true }
    params:
      build: bitbucket-repo
      build_args_file: build_args/build_args.json
      tag_as_latest: true
      cache_tag: latest
      tag: bitbucket-version/number

- name: build-docker-image-resource
  serial: true
  build_logs_to_retain: 5
  plan:
  - get: docker-image-resource
    trigger: true
  - task: build-docker-image-resource
    file: docker-image-resource/ci/build.yml
    input_mapping:
      docker-image-resource: docker-image-resource
    output_mapping:
      built-resource: docker-built-context
  - put: eugenmayer-docker-image-resource
    get_params: { skip_download : true }
    params:
      build: docker-built-context
      cache_tag: latest     

- name: build-docker-image-concourse-configurator
  serial: true
  build_logs_to_retain: 10
  plan:
  - get: docker-image-concourseci-configurator-repo
    trigger: true
  - get: alpine-image
    trigger: true
    params:
      skip_download: true
  - put: concourse-configurator-image
    get_params: { skip_download : true }
    params:
      build: docker-image-concourseci-configurator-repo
      tag_as_latest: true
      cache_tag: latest

- name: build-docker-image-concourse-worker-configurator
  serial: true
  build_logs_to_retain: 10
  plan:
  - get: docker-image-concourseci-worker-configurator-repo
    trigger: true
  - get: alpine-image
    trigger: true
    params:
      skip_download: true
  - put: concourse-worker-configurator-image
    get_params: { skip_download : true }
    params:
      build: docker-image-concourseci-worker-configurator-repo
      cache_tag: latest

- name: build-concourse-static-resource-image
  serial: true
  build_logs_to_retain: 5
  plan:
  - get: concourse-static-resource
    trigger: true
  - get: alpine-edge-image
    trigger: true
    params:
      skip_download: true
  - put: concourse-static-resource-image
    get_params: { skip_download : true }
    params:
      build: concourse-static-resource
      cache_tag: latest

#- name: build-hipchat-notification-resource-image
#  serial: true
#  build_logs_to_retain: 5
#  plan:
#  - get: hipchat-notification-resource-src
#    trigger: true
#  - put: hipchat-notification-resource-image
#    get_params: { skip_download : true }
#    params:
#      build: hipchat-notification-resource-src
#      cache_tag: latest

- name: build-docker-s3fs-image
  serial: true
  build_logs_to_retain: 5
  plan:
  - get: docker-image-s3fs
    trigger: true
  - get: debian-stretch-image
    trigger: true
    params:
      skip_download: true
  - put: eugenmayer-docker-image-aws-s3fs
    get_params: { skip_download : true }
    params:
      build: docker-image-s3fs
      cache_tag: latest

- name: build-docker-images-confluence
  serial: true
  build_logs_to_retain: 5
  plan:
    - get: adoptjdk-openjdk11-openj9-debian
      trigger: true
    - get: pipeline-versions-src
      trigger: true
    - get: atlassian-confluence-docker-image-src
      trigger: true
    # A fixed earlier version
#    - put: atlassian-confluence-docker-image
#      get_params: { skip_download : true }
#      params:
#        build: atlassian-confluence-docker-image-src
#        tag_static: ((confluence.early))
#        build_args:
#          CONFLUENCE_VERSION: ((confluence.early))
    # The latest version tagged as <version> and as 'latest'
    - put: atlassian-confluence-docker-image
      get_params: { skip_download : true }
      params:
        build: atlassian-confluence-docker-image-src
        tag_static: ((confluence.latest))
        tag_as_latest: true
        build_args:
          CONFLUENCE_VERSION: ((confluence.latest))

- name: build-docker-images-jira
  serial: true
  build_logs_to_retain: 5
  plan:
    - get: adoptjdk-openjdk11-debian
      trigger: true
    - get: pipeline-versions-src
      trigger: true
    - get: atlassian-jira-docker-image-src
      trigger: true
    # A fixed earlier version
#    - put: atlassian-jira-docker-image
#      get_params: { skip_download : true }
#      params:
#        build: atlassian-jira-docker-image-src
#        tag_static: en-((jira.early))
#        build_args:
#          JIRA_VERSION: ((jira.early))
    # The latest version tagged as <version> and as 'latest'
    - put: atlassian-jira-docker-image
      get_params: { skip_download : true }
      params:
        build: atlassian-jira-docker-image-src
        tag_static: en-((jira.latest))
        tag_as_latest: true
        build_args:
          JIRA_VERSION: ((jira.latest))

- name: build-docker-image-docker-client
  serial: true
  build_logs_to_retain: 10
  plan:
  - get: docker-client-docker-image-src
    trigger: true
  - get: docker-image
    trigger: true
    params:
      skip_download: true
  - put: docker-client-docker-image
    get_params: { skip_download : true }
    params:
      build: docker-client-docker-image-src
      cache_tag: latest

resources:
  - name: docker-image-s3fs
    type: git
    source:
      uri: https://github.com/EugenMayer/docker-image-s3fs
      branch: master

## RUNDECK
  - name: rundeck-repo
    type: git
    source:
      uri: https://github.com/EugenMayer/docker-image-rundeck
      branch: master      
  - name: rundeck-version
    type: concourse-git-semver-tag
    source:
      uri: https://github.com/EugenMayer/docker-image-rundeck
      branch: master
  - name: rundeck-image
    type: docker-image-resource-ng
    source:
      repository: eugenmayer/rundeck
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: latest

## bitbucket
  - name: bitbucket-repo
    type: git
    source:
      uri: https://github.com/EugenMayer/docker-image-atlassian-bitbucket
      branch: master

  - name: bitbucket-version
    type: concourse-git-semver-tag
    source:
      uri: https://github.com/EugenMayer/docker-image-atlassian-bitbucket
      branch: master

  - name: bitbucket-image
    type: docker-image-resource-ng
    source:
      repository: eugenmayer/bitbucket
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: latest
### Confluence

  - name: atlassian-confluence-docker-image-src
    type: git
    source:
      uri: https://github.com/EugenMayer/docker-image-atlassian-confluence
      branch: master

  - name: atlassian-confluence-docker-image
    type: docker-image-resource-ng
    source:
      repository: eugenmayer/confluence
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: latest

### Jira
  - name: atlassian-jira-docker-image-src
    type: git
    source:
      uri: https://github.com/EugenMayer/docker-image-atlassian-jira
      branch: master

  - name: atlassian-jira-docker-image
    type: docker-image-resource-ng
    source:
      repository: eugenmayer/jira
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: latest


### docker client
  - name: docker-client-docker-image-src
    type: git
    source:
      uri: https://github.com/EugenMayer/docker-image-docker-client
      branch: master

  - name: docker-client-docker-image
    type: docker-image-resource-ng
    source:
      repository: eugenmayer/docker-client
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: latest

### concourse
  - name: concourse-static-resource
    type: git
    source:
      uri: https://github.com/EugenMayer/concourse-static-resource
      branch: master

  - name: docker-image-resource
    type: git
    source:
      uri: https://github.com/EugenMayer/docker-image-resource-ng
      branch: develop

  - name: docker-image-concourseci-configurator-repo
    type: git
    source:
      uri: https://github.com/EugenMayer/docker-image-concourse-configurator
      branch: master

  - name: docker-image-concourseci-worker-configurator-repo
    type: git
    source:
      uri: https://github.com/EugenMayer/docker-image-concourse-worker-configurator
      branch: master

  - name: concourse-configurator-image
    type: docker-image-resource-ng
    source:
      repository: eugenmayer/concourse-configurator
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: 5.x

  - name: concourse-worker-configurator-image
    type: docker-image-resource-ng
    source:
      repository: eugenmayer/concourse-worker-configurator
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: latest

  - name: eugenmayer-docker-image-resource
    type: docker-image
    source:
      repository: eugenmayer/concourse-docker-image-resource
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: latest

  - name: concourse-static-resource-image
    type: docker-image-resource-ng
    source:
      repository: eugenmayer/concourse-static-resource
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: latest

  ### General
  - name: debian-stretch-image
    type: docker-image-resource-ng
    source:
      repository: debian
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: stretch

  - name: adoptjdk-openjdk11-debian
    type: docker-image-resource-ng
    source:
      repository: adoptopenjdk/openjdk11
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: debian

  - name: adoptjdk-openjdk11-openj9-debian
    type: docker-image-resource-ng
    source:
      repository: adoptopenjdk/openjdk11-openj9
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: debian


  - name: alpine-image
    type: docker-image-resource-ng
    source:
      repository: alpine
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: 3.6

  - name: docker-image
    type: docker-image-resource-ng
    source:
      repository: docker
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: latest

  - name: alpine-edge-image
    type: docker-image-resource-ng
    source:
      repository: alpine
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: edge

  - name: eugenmayer-docker-image-aws-s3fs
    type: docker-image-resource-ng
    source:
      repository: eugenmayer/aws-s3fs
      username: ((dockerhub.user))
      password: ((dockerhub.password))
      tag: latest
  - name: pipeline-src
    type: git
    source:
      uri: https://github.com/EugenMayer/concourse-our-open-pipelines
      branch: master

  - name: pipeline-versions-src
    type: git
    source:
      uri: https://github.com/EugenMayer/concourse-our-open-pipelines
      branch: master
      paths: ['ci/versions.yml']


resource_types:
- name: docker-image-resource-ng
  type: docker-image
  privileged: true
  source:
    repository: eugenmayer/concourse-docker-image-resource
    tag: latest
- name: concourse-git-semver-tag
  type: docker-image
  source:
    repository: eugenmayer/concourse-git-semver-tag-resource
